-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXVg9xQcPW0TyM9yj
95yCIYTZ0hIyxUU6MBqLjWrzlFCgCgYIKoZIzj0DAQehRANCAASd1IlCe41uSmRM
GkIy3oJDej7yuuBrbufRFIMqDvKX/lJFwdgMcgrdVwR6pE1l5wxVVm/gL/65KJ+u
pt+PneYG
-----END PRIVATE KEY-----